Controllers/CarController.cs
using FribergCarRentals_DAL.Data;
using Microsoft.AspNetCore.Mvc;

namespace FribergCarRentals_GOhman.Controllers
{
    public class CarController : Controller
    {
        private readonly ICar carRepo;

        public CarController(ICar carRepo)
        {
            this.carRepo = carRepo;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(carRepo.GetAll());
        }

        public ActionResult Details(int id)
        {
            return View(carRepo.GetById(id));
        }

        public IActionResult BookCar(int id)
        {
            HttpContext.Session.SetString("carId", id.ToString());
            return RedirectToAction("SelectDate", "Booking");
        }
    }
}

Controllers/LoginController.cs
using FribergCarRentals_DAL.Data;
using FribergCarRentals_DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FribergCarRentals_GOhman.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUser userRepo;
        private readonly AuthLogin authLogin;
        private readonly IHttpContextAccessor httpContextAccessor;

        public LoginController(IUser userRepo, AuthLogin authLogin, IHttpContextAccessor httpContextAccessor)
        {
            this.userRepo = userRepo;
            this.authLogin = authLogin;
            this.httpContextAccessor = httpContextAccessor;
        }
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserAccount user)
        {
            UserAccount u = authLogin.GetUser(user.Email, user.Password);

            if (u is not null)
            {
                HttpContext.Session.SetString("LoggedInAccount", JsonConvert.SerializeObject(u));
                HttpContext.Session.SetString("Role", u.Role.ToString());
                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddMinutes(1);
                httpContextAccessor.HttpContext.Response.Cookies.Append("LoggedInCookie", JsonConvert.SerializeObject(u), options);

                if (HttpContext.Session.GetString("bookingLogin") == "booking")
                {
                    return RedirectToAction("SelectDate", "Booking");
                }
                return RedirectToAction("Index", "Home");
            }
            ViewBag.NotFound = "Invalid username/password. Try again.";
            return View();
        }

        public IActionResult Logout()
        {
            try
            {
                httpContextAccessor.HttpContext.Response.Cookies.Delete("LoggedInCookie");
                string style = HttpContext.Session.GetString("style");
                HttpContext.Session.Clear();
                HttpContext.Session.SetString("style", style);

                return RedirectToAction("Index", "Home", null);
            }
            catch
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View(new UserAccount());
        }

        // POST: AuthLogin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UserAccount user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if(authLogin.CheckUsername(user.Email) != null)
                    {
                        ViewBag.UsernameError = "A user with that email is already registered";
                        return View();
                    }
                    userRepo.Add(user);
                    UserAccount currUser = authLogin.GetUser(user.Email, user.Password);
                    HttpContext.Session.SetString("LoggedInAccount", JsonConvert.SerializeObject(currUser));
                    HttpContext.Session.SetString("Role", currUser.Role.ToString());

                    if (HttpContext.Session.GetString("bookingLogin") == "booking")
                    {
                        return RedirectToAction("SelectDate", "Booking");
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/UserController.cs
using FribergCarRentals_GOhman.Data;
using FribergCarRentals_GOhman.Models;
using Microsoft.AspNetCore.Mvc;

namespace FribergCarRentals_GOhman.Controllers
{
    public class UserController : Controller
    {
        private readonly IUser userRepository;

        public UserController(IUser userRepository) 
        {
            this.userRepository = userRepository;
        }

        public ActionResult Index()
        {
            return View(userRepository.GetAll());
        }

        public ActionResult Details(int id)
        {
            return View(userRepository.GetById(id));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userRepository.Add(user);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View(userRepository.GetById(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userRepository.Update(user);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View(userRepository.GetById(id));
        }

        // POST: CarController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(User user)
        {
            try
            {
                userRepository.Delete(user);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_AdminLayout.cshtml
@using Newtonsoft.Json
@using Newtonsoft.Json.Linq
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FribergCarRentals_GOhman</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @{
        @if (string.IsNullOrEmpty(Context.Session.GetString("style")) || Context.Session.GetString("style") == "new")
        {
            <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        }
        @if (Context.Session.GetString("style") == "retro")
        {
            <link rel="stylesheet" href="~/css/siteRetro.css" asp-append-version="true" />
        }
    }
    <link rel="stylesheet" href="~/FribergCarRentals_GOhman.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/9092ca5d2a.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index"><img style="height: 3em; width: 3em;" src="~/Friberg_LOGO.PNG" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="position-absolute end-0 d-flex align-items-center" style="top: 20%; left: 50%; transform: translateY(-50%);">
                @{
                    if (SessionHelper.CheckSessionLogin(Context))
                    {
                        <h6 style="color: red;">ADMIN ACCESS!</h6>
                    }
                }
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @{
                        if (string.IsNullOrEmpty(Context.Session.GetString("style")) || Context.Session.GetString("style") == "new")
                        {
                            <a asp-controller="Home" asp-action="Toggle"><i class="fa-solid fa-moon style-switch"></i> </a>
                        }
                        if (Context.Session.GetString("style") == "retro")
                        {
                            <a asp-controller="Home" asp-action="Toggle"><i class="fa-regular fa-moon style-switch"></i> </a>
                        }
                    }
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark btn" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn" asp-area="Admin" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn" asp-area="Admin" asp-controller="Booking" asp-action="Index">Bookings</a>
                        </li>
                    </ul>

                    <div class="position-absolute end-0 d-flex align-items-center" style="top: 50%; transform: translateY(-50%);">

                        @{
                            if (SessionHelper.CheckSessionLogin(Context))
                            {
                                <div class="nav-item login-nav">
                                    <a class="btn btn-danger" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </div>
                            }
                            else
                            {
                                <div class="nav-item login-nav">
                                    <a class="btn btn-primary" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="box-stuff">
                @RenderBody()
                
            </div>
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FribergCarRentals_GOhman
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Newtonsoft.Json
@using Newtonsoft.Json.Linq
<!DOCTYPE html>
<html lang="en">
    
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FribergCarRentals_GOhman</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  @*   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FribergCarRentals_GOhman.styles.css" asp-append-version="true" />
      <script src="https://kit.fontawesome.com/9092ca5d2a.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FribergCarRentals_GOhman</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        @{

                        }
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FribergCarRentals_GOhman - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
@using Newtonsoft.Json
@using Newtonsoft.Json.Linq
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FribergCarRentals_GOhman</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FribergCarRentals_GOhman.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/9092ca5d2a.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FribergCarRentals_GOhman</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FribergCarRentals_GOhman - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_UserLayout.cshtml
@using Newtonsoft.Json
@using Newtonsoft.Json.Linq
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FribergCarRentals_GOhman</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    @{
        @if (string.IsNullOrEmpty(Context.Session.GetString("style")) || Context.Session.GetString("style") == "new")
        {
            <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        }
        @if (Context.Session.GetString("style") == "retro")
        {
            <link rel="stylesheet" href="~/css/siteRetro.css" asp-append-version="true" />
        }
    }

    <link rel="stylesheet" href="~/FribergCarRentals_GOhman.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/9092ca5d2a.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img style="height: 3em; width: 3em;" src="~/Friberg_LOGO.PNG" /></a>
              
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @{
                        if (string.IsNullOrEmpty(Context.Session.GetString("style")) || Context.Session.GetString("style") == "new")
                        {
                            <a asp-controller="Home" asp-action="Toggle"><i class="fa-solid fa-moon style-switch"></i> </a>
                        }
                        if (Context.Session.GetString("style") == "retro")
                        {
                            <a asp-controller="Home" asp-action="Toggle"><i class="fa-regular fa-moon style-switch"></i> </a>
                        }
                    }
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark btn" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn" asp-controller="Booking" asp-action="Index">Booking</a>
                        </li>
                    </ul>

                    <div class="position-absolute end-0 d-flex align-items-center" style="top: 50%; transform: translateY(-50%);">

                        @{
                            if (SessionHelper.CheckSessionLogin(Context))
                            {
                                <div class="nav-item login-nav">
                                    <a class="btn btn-danger" asp-controller="Login" asp-action="Index">Logout</a>
                                </div>
                            }
                            else
                            {
                                <div class="nav-item login-nav">
                                    <a class="btn btn-primary" asp-controller="Login" asp-action="Login">Login</a>
                                </div>
                            }
                        }
                    </div>

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="box-stuff">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FribergCarRentals_GOhman - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>